import{a as v,S as q,i as s}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="56042782-24f3f911d5d7a62af18e10af9",M="https://pixabay.com/api/";async function m(r,t=1){const a={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await v.get(M,{params:a})).data}const h=document.querySelector(".gallery"),y=document.querySelector("#loader"),g=document.querySelector("#load-more");let B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=r.map(({webformatURL:a,largeImageURL:n,tags:e,likes:o,views:i,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${o}</p>
        <p class="info-item"><b>Views</b> ${i}</p>
        <p class="info-item"><b>Comments</b> ${w}</p>
        <p class="info-item"><b>Downloads</b> ${S}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){h.innerHTML=""}function L(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}function b(){g.classList.remove("is-hidden")}function u(){g.classList.add("is-hidden")}const $=document.querySelector("#search-form"),O=document.querySelector("#load-more");let d="",l=1,f=0;$.addEventListener("submit",x);O.addEventListener("click",A);async function x(r){if(r.preventDefault(),d=r.currentTarget.elements.searchQuery.value.trim(),!d){s.warning({title:"Warning",message:"Please enter a search query!"});return}l=1,E(),u(),L();try{const t=await m(d,l);if(f=t.totalHits,t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),c();return}p(t.hits),c(),f>15?b():s.info({message:"We're sorry, but you've reached the end of search results."})}catch{s.error({title:"Error",message:"Something went wrong. Please try again later."}),c()}}async function A(){l+=1,u(),L();try{const r=await m(d,l);p(r.hits),c();const t=Math.ceil(f/15);l>=t?(u(),s.info({message:"We're sorry, but you've reached the end of search results."})):b(),D()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later."}),c()}}function D(){const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
